# If you modify this file, please also update the `clippy_utils` version in `bevy_lint/Cargo.toml`
# and the compatibility table in `bevy_lint/README.md`.

[toolchain]
# Writing custom lints requires using nightly Rust. We pin to a specific version of nightly version
# so that builds are reproducible.
channel = "stable-x86_64-pc-windows-msvc"
# These components are required to use `rustc` crates.
components = ["rustc-dev", "llvm-tools-preview"]
